name: build

on:
  push:
    branches: [ main, smoke-aws-generate-2.x, smoke-aws-generate-1.x ]
  pull_request:
    branches: [ main, smoke-aws-generate-2.x, smoke-aws-generate-1.x ]
      
jobs:
  Build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        swift: ["5.5", "5.4.3", "5.3.3", "5.2.5"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: marcprux/setup-swift@a990bc57c514a77d232b645843ade099af21aa5e
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
